language: generic

os:
  - linux
  - osx

sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=/opt/ghc/8.4.4/bin:/opt/cabal/head/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install ghc cabal-install; fi
  - travis_retry cabal v2-update

script:
  - cabal v2-build all
  - cabal v2-exec -- which source-server
  - cabal v2-exec -- which source-client

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.4.4
    - cabal-install-head

cache:
  directories:
    - ~/.cabal
    - ~/.ghc

matrix:
  fast_finish: true
  allow_failures:
  - os: osx
